### PR TITLE
Make pep8 modifications to views.py

### PR DESCRIPTION
**Pull request by adamrp**
I did not review any of the content in this file. I only made style changes necessary to comply with pep8 guidelines.

Related to #24

### CODE REVIEW

**Comment by adamrp** [comment]
Hold off on review/merge until further notice -- I'm updating all of the code to comply with the guidelines

**Comment by adamrp** [comment]
This took a lot longer than I hoped! I still have one more file to fix (Andrew's BioModules file), and I've made a lot of headway there already. I should be able to finish this tomorrow (Tues).

**Comment by AndreaEdwards** [comment]
@adamrp thanks for doing this! Can you come in tomorrow so we can briefly go over the changes? I will be working in SEEC for most of the day tomorrow.

**Comment by adamrp** [comment]
Okay, all of the changes are in. @AndreaEdwards sounds good, let's coordinate via email.

**Comment by adamrp** [comment]
Note to all: this PR touches a lot of files, so merging is high priority. Anyone else editing the files that this PR modifies will likely introduce annoying conflicts.

**Pull request merged**
